### ISSUE TITLE
ipv6 查询报错

### ISSUE THREAD

**Issue by vixiaobai** [tagphi/czdb-search-java#14]
分别查询192.168.1.1与fd00:6868:6868::17e,使用相同的密钥在处理ipv6地址时出现解密错误

![image](https://github.com/user-attachments/assets/0e6c1c0c-f43c-4d68-bb79-b0207b4bb919)
![image](https://github.com/user-attachments/assets/fc057e1e-08ab-4969-bad4-a4bb6bfac758)

```
Exception in thread "main" javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
	at java.base/com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java:1011)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at net.cz88.czdb.entity.DecryptedBlock.decrypt(DecryptedBlock.java:133)
	at net.cz88.czdb.utils.HyperHeaderDecoder.decrypt(HyperHeaderDecoder.java:40)
	at net.cz88.czdb.DbSearcher.<init>(DbSearcher.java:90)
	at org.jeecg.common.system.util.IPUtil.getIpv6Add(IPUtil.java:57)
	at org.jeecg.common.system.util.IPUtil.main(IPUtil.java:31)
```

**Comment by shuaigg2024** [comment]
方便把你的v6库和密钥发一下吗

**Comment by shuaigg2024** [comment]
联系邮箱：shuai.gao@rtbasia.com

**Comment by craigliu** [comment]
你是否用了最新的版本？ipv4的库和ipv6不是一个文件，现在如果用v4库查询v6地址，应该会报一个地址格式错误的异常

**Comment by vixiaobai** [comment]
11月26 号下载的版本， 确认v6与v4库不是同一个文件
![image](https://github.com/user-attachments/assets/6270e10b-2e82-44fc-87ff-3c0e03f71489)

**Comment by craigliu** [comment]
把你的库和密钥发这个邮箱shuai.gao@rtbasia.com 我们看看

**Comment by vixiaobai** [comment]
ipv6 的文件太大，被github拦截了，没办法发送过去，2024年11月26号下载的文件
密钥是：&nbsp;bteiBajP8zrdmxnFZBfIbg==






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tagphi/czdb-search-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月13日(星期五) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tagphi/czdb-search-java] ipv6 查询报错 (Issue #14)





 
方便把你的v6库和密钥发一下吗
